name: loading_more_listview
description: A Simple Flutter ListView Widget with an Indicator at the end of it and a Callback when users Scroll toward the end of the List.
version: 1.0.1
author: Ahmad Givekesh <ahmadgivekesh@gmail.com>
homepage: https://github.com/jinxul/loading-more-listview/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: