name: loading_more_listview
description: A simple LoadingMore ListView
version: 1.0.0
author: Ahmad Givekesh <ahmadgivekesh@gmail.com>
homepage: https://github.com/jinxul/loading-more-listview/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: